# Generated by Django 3.1.7 on 2021-05-05 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_day',
            field=models.DateField(default=datetime.date(2021, 5, 5)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('U', 'Unsure'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=10),
        ),
    ]
