# Generated by Django 2.2.3 on 2021-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210512_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='header.jpg', upload_to='media/header_pictures'),
        ),
    ]
