# Generated by Django 2.2.3 on 2021-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210516_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='header.jpg', upload_to='header_pictures'),
        ),
    ]
