# Generated by Django 3.1.7 on 2021-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(max_length=255),
        ),
    ]
